{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"f_BASE\",\"dim_cursos\",\"dim_exatas_humanas\",\"dim_campus\",\"dim_turno\",\"dim_situacao\",\"dim_forma_pgto\",\"dim_genero\",\"dim_pcd\",\"dim_estagio\",\"dim_diploma\",\"MEDIDAS\",\"MEDIDAS ALUNOS\",\"dim_alunos\",\"MEDIDAS FINANCEIRA\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.2054.0 (24.12)+334ca1c95b576cc53924655643b0d36f21caac55"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "AutoDetected_6be0b699-7e6d-4746-859a-18a2ad19ae31",
        "fromColumn": "Curso",
        "fromTable": "f_BASE",
        "toColumn": "Curso",
        "toTable": "dim_cursos"
      },
      {
        "name": "AutoDetected_239122ed-5c5f-45db-aa22-1c7bb1821e9e",
        "fromColumn": "EXATAS HUMANAS",
        "fromTable": "f_BASE",
        "toColumn": "EXATAS HUMANAS",
        "toTable": "dim_exatas_humanas"
      },
      {
        "name": "AutoDetected_bfd56f3a-8f3e-4623-91fe-d25d73a9fcc8",
        "fromColumn": "Campus",
        "fromTable": "f_BASE",
        "toColumn": "Campus",
        "toTable": "dim_campus"
      },
      {
        "name": "AutoDetected_c24ae75f-2353-4d25-bb44-6fb95ba0f590",
        "fromColumn": "Turno",
        "fromTable": "f_BASE",
        "toColumn": "Turno",
        "toTable": "dim_turno"
      },
      {
        "name": "AutoDetected_8de7ae1e-a996-4070-9393-5fd1cbf3a2d0",
        "fromColumn": "Situação",
        "fromTable": "f_BASE",
        "toColumn": "Situação",
        "toTable": "dim_situacao"
      },
      {
        "name": "AutoDetected_40ff28bd-15db-4bd3-8b5d-153abfa29cf5",
        "fromColumn": "FORMA PGTO",
        "fromTable": "f_BASE",
        "toColumn": "FORMA PGTO",
        "toTable": "dim_forma_pgto"
      },
      {
        "name": "AutoDetected_6cb31d6d-5d8c-4fed-8006-1c982ce8d241",
        "fromColumn": "GENERO",
        "fromTable": "f_BASE",
        "toColumn": "GENERO",
        "toTable": "dim_genero"
      },
      {
        "name": "AutoDetected_0a24e3ff-6d62-481f-88b4-4733adebcbe4",
        "fromColumn": "PCD",
        "fromTable": "f_BASE",
        "toColumn": "PCD",
        "toTable": "dim_pcd"
      },
      {
        "name": "AutoDetected_c58a031a-7bf4-49b7-a88c-c15526fe3251",
        "fromColumn": "ESTAGIO",
        "fromTable": "f_BASE",
        "toColumn": "ESTAGIO",
        "toTable": "dim_estagio"
      },
      {
        "name": "AutoDetected_7361bcb2-5947-446a-9b66-a104e1f52b31",
        "fromColumn": "PEGO DIPLOMA",
        "fromTable": "f_BASE",
        "toColumn": "PEGO DIPLOMA",
        "toTable": "dim_diploma"
      },
      {
        "name": "238d4be8-28ce-f010-de2c-a5cbc9104524",
        "fromColumn": "Matricula",
        "fromTable": "f_BASE",
        "toColumn": "Matricula",
        "toTable": "dim_alunos"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "f_BASE",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Alunos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05fec580-f297-4d9c-8dcd-17f408fd0b59",
            "sourceColumn": "Alunos",
            "summarizeBy": "none"
          },
          {
            "name": "Matricula",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "691d04ae-40a9-4298-a09a-74ebea344aca",
            "sourceColumn": "Matricula",
            "summarizeBy": "none"
          },
          {
            "name": "End",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb5d9062-ec76-487e-9e34-3a8fd1677ad5",
            "sourceColumn": "End",
            "summarizeBy": "none"
          },
          {
            "name": "Foto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf35fa6b-8706-406f-88d7-b89b67694c58",
            "sourceColumn": "Foto",
            "summarizeBy": "none"
          },
          {
            "name": "CPF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7ba7a7a-e6e3-4ad6-ae7d-6441e087dfbe",
            "sourceColumn": "CPF",
            "summarizeBy": "none"
          },
          {
            "name": "Curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a28b52ba-b0c2-48f2-bd14-4b72e3ea2407",
            "sourceColumn": "Curso",
            "summarizeBy": "none"
          },
          {
            "name": "EXATAS HUMANAS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60696d24-2488-456e-ad82-cab046352608",
            "sourceColumn": "EXATAS HUMANAS",
            "summarizeBy": "none"
          },
          {
            "name": "IMG  EXATAS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca448a04-e065-4031-b8ef-8fb4e5af4898",
            "sourceColumn": "IMG  EXATAS",
            "summarizeBy": "none"
          },
          {
            "name": "Nota de Aprovação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c8cf02b7-446d-4fc1-b243-75303f6d99ff",
            "sourceColumn": "Nota de Aprovação",
            "summarizeBy": "none"
          },
          {
            "name": "Campus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d4a1b0b2-c810-42a3-8b2c-12b562439654",
            "sourceColumn": "Campus",
            "summarizeBy": "none"
          },
          {
            "name": "Turno",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adb05436-bce3-4a58-827e-4affcb9a1f79",
            "sourceColumn": "Turno",
            "summarizeBy": "none"
          },
          {
            "name": "Mensalidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "b4c58afc-9e16-47c5-96f9-bb7b799b02cb",
            "sourceColumn": "Mensalidade",
            "summarizeBy": "none"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "decf9a67-9918-4726-acbf-f05aa131b710",
            "sourceColumn": "Ano",
            "summarizeBy": "none"
          },
          {
            "name": "Situação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14363648-94e6-47d2-9be2-d5ce32c0cffe",
            "sourceColumn": "Situação",
            "summarizeBy": "none"
          },
          {
            "name": "FORMA PGTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8cd60a4-f769-43f4-9b05-ab02fff434ec",
            "sourceColumn": "FORMA PGTO",
            "summarizeBy": "none"
          },
          {
            "name": "GENERO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b6d446e-d15d-4e55-ba15-93d5262bf08a",
            "sourceColumn": "GENERO",
            "summarizeBy": "none"
          },
          {
            "name": "IDADE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b5d983ab-1ffe-42a1-a0f4-ceafde7715f5",
            "sourceColumn": "IDADE",
            "summarizeBy": "sum"
          },
          {
            "name": "Pegou DP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "127eb38e-1e71-4e48-b0e2-aab7ddde5e84",
            "sourceColumn": "Pegou DP",
            "summarizeBy": "none"
          },
          {
            "name": "PCD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "862ea9a5-7f0f-4e65-b85d-f6057b85d5f5",
            "sourceColumn": "PCD",
            "summarizeBy": "none"
          },
          {
            "name": "ESTAGIO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c45cc6d-8088-4a0b-8fec-4cd2af3421de",
            "sourceColumn": "ESTAGIO",
            "summarizeBy": "none"
          },
          {
            "name": "DPS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ece62226-cb40-488d-8d14-dc525c21678a",
            "sourceColumn": "DPS",
            "summarizeBy": "none"
          },
          {
            "name": "PEGO DIPLOMA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ad9082a-8b9c-4457-a17b-e07de2b82c37",
            "sourceColumn": "PEGO DIPLOMA",
            "summarizeBy": "none"
          },
          {
            "name": "ICONE DIPLOMA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "",
              "IF(f_BASE[PEGO DIPLOMA] = \"PEGOU DIPLOMA\", \"https://e7.pngegg.com/pngimages/599/892/png-clipart-x-mark-computer-icons-sign-others-miscellaneous-logo-thumbnail.png\",",
              "                            \"https://w7.pngwing.com/pngs/595/505/png-transparent-computer-icons-error-closeup-miscellaneous-text-logo-thumbnail.png\"",
              "",
              "",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "68be5c88-7eb7-43c6-bc2c-a175e684d4cc",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "3b6215b9-b879-4011-a6bb-a24dac69086d",
        "partitions": [
          {
            "name": "f_BASE",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(\"C:\\Users\\Anderson\\OneDrive\\Área de Trabalho\\rapha\\materiais_bi\\modulo 4\\Universidade_YTO.xlsx\"), null, true),",
                "    Tabela13_Table = Fonte{[Item=\"Tabela13\",Kind=\"Table\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Tabela13_Table,{{\"Matricula\", type text}, {\"Alunos\", type text}, {\"End\", type text}, {\"Foto\", type text}, {\"Curso\", type text}, {\"EXATAS HUMANAS\", type text}, {\"CPF\", type text}, {\"IMG  EXATAS\", type text}, {\"Campus\", type text}, {\"Turno\", type text}, {\"Situação\", type text}, {\"FORMA PGTO\", type text}, {\"GENERO\", type text}, {\"Pegou DP\", type text}, {\"PCD\", type text}, {\"ESTAGIO\", type text}, {\"DPS\", type text}, {\"IDADE\", Int64.Type}, {\"Ano\", type text}, {\"Mensalidade\", type number}, {\"Nota de Aprovação\", type text}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Tipo Alterado\",{{\"PEGO DIPLOMA\", \"PEGO DIPLOMA\"}}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Colunas Renomeadas\",\"CIENCIAS UHMANAS\",\"CIENCIAS HUMANAS\",Replacer.ReplaceText,{\"EXATAS HUMANAS\"})",
                "in",
                "    #\"Valor Substituído\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_cursos",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "907d4f10-d443-4e7b-aa89-b65374c8c473",
            "sourceColumn": "Curso",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "57f48aba-ea03-49ea-9422-21e0043c0bab",
        "partitions": [
          {
            "name": "dim_cursos",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = f_BASE,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"Curso\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Outras Colunas Removidas\")",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_exatas_humanas",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "EXATAS HUMANAS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e14fbdf4-a281-4709-9284-1aca85c16c17",
            "sourceColumn": "EXATAS HUMANAS",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d217a2c1-c271-461b-a775-7191ca3252c0",
        "partitions": [
          {
            "name": "dim_exatas_humanas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = f_BASE,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"EXATAS HUMANAS\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Outras Colunas Removidas\")",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_campus",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Campus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09d94b44-66b5-4038-9672-ee26e5fc3f0d",
            "sourceColumn": "Campus",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8bb0e7e1-23c9-4aa1-a4c0-8b56e9bc97d3",
        "partitions": [
          {
            "name": "dim_campus",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = f_BASE,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"Campus\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Outras Colunas Removidas\")",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_turno",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Turno",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d1e30d50-f0bb-4abe-a8c2-ac73e407660e",
            "sourceColumn": "Turno",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2158f22d-a57a-435a-8857-d1aff83b9dec",
        "partitions": [
          {
            "name": "dim_turno",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = f_BASE,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"Turno\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Outras Colunas Removidas\")",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_situacao",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Situação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0afa2257-1dce-4e99-acd8-a6e4c7c31a1e",
            "sourceColumn": "Situação",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "320779e4-1f8b-40d2-9ff5-aa0a771c0195",
        "partitions": [
          {
            "name": "dim_situacao",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = f_BASE,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"Situação\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Outras Colunas Removidas\")",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_forma_pgto",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FORMA PGTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e88cd908-faeb-4166-b204-731e6ad6c026",
            "sourceColumn": "FORMA PGTO",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d02d7300-98c4-400c-ab48-2b986b5e2905",
        "partitions": [
          {
            "name": "dim_forma_pgto",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = f_BASE,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"FORMA PGTO\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Outras Colunas Removidas\")",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_genero",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "GENERO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5d6ee06-5026-4c89-b27c-81c7632808af",
            "sourceColumn": "GENERO",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "59d4c8d2-9359-4e51-bebb-f37d5bdea5fb",
        "partitions": [
          {
            "name": "dim_genero",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = f_BASE,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"GENERO\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Outras Colunas Removidas\")",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_pcd",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PCD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2aaa986e-c679-4474-b173-b2d62836809e",
            "sourceColumn": "PCD",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "680ab361-041e-41ca-996a-6d09bf559be5",
        "partitions": [
          {
            "name": "dim_pcd",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = f_BASE,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"PCD\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Outras Colunas Removidas\")",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_estagio",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ESTAGIO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08b16090-fe3e-49a7-a8e1-3df72d896756",
            "sourceColumn": "ESTAGIO",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "75d9e31c-4cae-46ec-8595-8f47788e43b8",
        "partitions": [
          {
            "name": "dim_estagio",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = f_BASE,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"ESTAGIO\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Outras Colunas Removidas\")",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_diploma",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PEGO DIPLOMA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f04381e1-c50a-4c77-ab10-08c91e736582",
            "sourceColumn": "PEGO DIPLOMA",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f6323914-8b6c-49f0-9279-11bf84855dc9",
        "partitions": [
          {
            "name": "dim_diploma",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = f_BASE,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"PEGO DIPLOMA\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Outras Colunas Removidas\")",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MEDIDAS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "777b961b-0cfb-45fb-8805-f5afda95b9b1",
        "measures": [
          {
            "name": "FAT_INADIMPLENTES",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "CALCULATE(SUM(f_BASE[Mensalidade])",
              "                    ,FILTER(dim_situacao,dim_situacao[Situação] = \"Não Pago\"))"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "032c3b83-b4ee-4e8b-b95c-0aaa6f7f098a"
          },
          {
            "name": "TT MATRICULAS",
            "expression": [
              "",
              "",
              "    VAR MTL = COUNTA(f_BASE[Matricula])",
              "",
              "    RETURN MTL  //RETURN PRA VARIAVEL DAR O VALOR SE N TIVER O VALOR N APARECE NA MEDIDA",
              "//^^^^ACIMA FEITO POR MEIO DE VARIAVEL ^^^^",
              "",
              "//TT MATRICULAS = COUNTA(f_BASE[Matricula])"
            ],
            "formatString": "0",
            "lineageTag": "2816e94a-5b57-47c8-8737-67505a673c76"
          },
          {
            "name": "MEDIA DE IDADE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "    VAR MEDIA_AL = AVERAGE(f_BASE[IDADE])    // EXPRESSÃO QUE SERÁ ATRIBUÍDA PARA A VARIÁVEL",
              "    RETURN MEDIA_AL",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "988fb31b-55f5-407d-ab0f-2847f1df79eb"
          },
          {
            "name": "FAT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "CALCULATE(SUM(f_BASE[Mensalidade])",
              "        , FILTER(dim_situacao, dim_situacao[Situação] = \"PAGO\"))"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "35cc29a0-6edb-4ebd-a694-51005ea13d20"
          },
          {
            "name": "% POrC TT",
            "expression": [
              "",
              "",
              "VAR ValorFiltro = CALCULATE(SUM(f_BASE[Mensalidade]), ALL(f_BASE))",
              "",
              "VAR ValorVenda = [FAT] ",
              "",
              "RETURN",
              "DIVIDE(ValorVenda, ValorFiltro)",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0ddf44be-8648-4f82-bbc0-e504667914d4"
          },
          {
            "name": "% NAO PG",
            "expression": "FORMAT(DIVIDE([TT NAO PAGO],[TT MATRICULAS]), \"PERCENT\")",
            "lineageTag": "056c4128-b6ec-41e3-9dcb-2d05274aed53"
          },
          {
            "name": "FAT REAL",
            "expression": "FORMAT([FAT], \"R$\\ #,0.00\", \"pt-br\")",
            "lineageTag": "d9e8fbc9-7107-46e1-863d-217d8f0e63ef"
          },
          {
            "name": "TOTAL INADIMPLENTES",
            "expression": [
              "CALCULATE(COUNTA(f_BASE[Mensalidade])",
              "                    ,FILTER(dim_situacao,dim_situacao[Situação] = \"Não Pago\")) + 0"
            ],
            "formatString": "0",
            "lineageTag": "4cf8fdf8-d259-45d2-b5f4-7bfc5b5aa28e"
          },
          {
            "name": "TT PAGO",
            "expression": [
              "CALCULATE(COUNTA(f_BASE[Mensalidade])",
              "            ,FILTER(dim_situacao,dim_situacao[Situação] = \"Pago\"))"
            ],
            "formatString": "0",
            "lineageTag": "6b3d4cb5-cdad-4202-b328-8aa16398868c"
          },
          {
            "name": "% PAGO",
            "expression": "FORMAT(DIVIDE([TT PAGO],[TT MATRICULAS]) , \"PERCENT\")",
            "lineageTag": "041f57ff-b920-4439-9453-c5b358337a2d"
          },
          {
            "name": "TTL ALUNOS EM DP",
            "expression": [
              "CALCULATE(COUNT(f_BASE[Pegou DP])",
              "                , FILTER(dim_alunos, dim_alunos[DPS] = \"DP\"))",
              "        "
            ],
            "formatString": "0",
            "lineageTag": "664d02bf-dde5-4e39-867e-dd5f26252335"
          }
        ],
        "partitions": [
          {
            "name": "MEDIDAS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MEDIDAS ALUNOS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "8b138ed6-6efc-4840-9ca7-c51eecda46f7",
        "measures": [
          {
            "name": "ALUNO",
            "expression": "SELECTEDVALUE(f_BASE[Alunos], \"NENHUM SELECIONADO\")",
            "lineageTag": "6c56b34a-242e-4baf-84a1-ea193b645d2a"
          },
          {
            "name": "ENDERECO",
            "expression": "SELECTEDVALUE(f_BASE[End], \"-\")",
            "lineageTag": "ded200d0-8f54-4306-94cb-95a80a1c0661"
          },
          {
            "name": "CPF",
            "expression": "SELECTEDVALUE(f_BASE[CPF], \"-\")",
            "lineageTag": "68c5bbd1-0252-4390-bea7-57c013b394f3"
          },
          {
            "name": "MENSALIDADE",
            "expression": [
              "",
              "",
              " VAR Mens= SELECTEDVALUE(f_BASE[Mensalidade], \"-\" )",
              " VAR txt = \"R$ \"",
              " RETURN",
              " CONCATENATE(txt, Mens)",
              "",
              ""
            ],
            "lineageTag": "fdea2cd1-02ce-4b56-ab38-881743a8b496"
          },
          {
            "name": "TURNO",
            "expression": [
              "",
              "VAR TURNO = SELECTEDVALUE(f_BASE[Turno], \"-\")",
              "RETURN TURNO"
            ],
            "lineageTag": "9bda2627-6a0f-44c0-b592-880c7e221951"
          },
          {
            "name": "SEXO",
            "expression": [
              "",
              "var genero = SELECTEDVALUE(f_BASE[GENERO], \"-\")",
              "return genero"
            ],
            "lineageTag": "c40b5453-6daf-46d5-acda-42159c6dfe02"
          },
          {
            "name": "IDADE",
            "expression": [
              "",
              "",
              "    \"Idade: \" & SELECTEDVALUE(f_BASE[IDADE], \"-\")"
            ],
            "lineageTag": "f482bce8-d179-4b11-8498-5515fff84da6"
          },
          {
            "name": "CURSO",
            "expression": [
              "",
              "",
              "VAR FACUL = SELECTEDVALUE(f_BASE[Curso], \"-\")",
              "RETURN \"Curso: \" & FACUL"
            ],
            "lineageTag": "f4a3ab1c-e76a-4c14-8de9-071b360e083a"
          },
          {
            "name": "DP",
            "expression": [
              "",
              "",
              "\"DPS: \"&SELECTEDVALUE(f_BASE[DPS], \"-\")"
            ],
            "lineageTag": "8a8c987c-c0c7-42f7-84d5-fa53c5510bf3"
          },
          {
            "name": "CAMPUS",
            "expression": [
              "",
              "",
              "VAR CAMP = SELECTEDVALUE(f_BASE[Campus], \"-\")",
              "VAR TEX = \"Campus: \"",
              "VAR CONC = TEX & CAMP",
              "RETURN CONC",
              ""
            ],
            "lineageTag": "4fab88ed-61ed-4b0e-8979-c6c981f5ed81"
          },
          {
            "name": "RA",
            "expression": [
              "",
              "",
              "VAR ra = SELECTEDVALUE(f_BASE[Matricula], \"-\")",
              "",
              "VAR tex = \"RA: \"",
              "RETURN CONCATENATE(tex, ra)"
            ],
            "lineageTag": "e6417385-4821-423a-82ea-590ad97717cd"
          }
        ],
        "partitions": [
          {
            "name": "MEDIDAS ALUNOS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_alunos",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Alunos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a9e723e-03ad-4cf4-b908-1e4dccb98361",
            "sourceColumn": "Alunos",
            "summarizeBy": "none"
          },
          {
            "name": "Matricula",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2c62fa6-4952-4793-a994-c5af1893d6bd",
            "sourceColumn": "Matricula",
            "summarizeBy": "none"
          },
          {
            "name": "DPS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62a5dac9-6984-4c54-952e-18cf7ae4ec79",
            "sourceColumn": "DPS",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "eada9b09-bc1c-4bfe-a347-d33f98e93c42",
        "partitions": [
          {
            "name": "dim_alunos",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = f_BASE,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"Alunos\", \"Matricula\", \"DPS\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Outras Colunas Removidas\", {\"Matricula\"})",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MEDIDAS FINANCEIRA",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "4dd278f8-4206-4f73-b0e8-d2c9e6c1e152",
        "measures": [
          {
            "name": "MINIMO",
            "expression": "0",
            "formatString": "0",
            "lineageTag": "080dde0e-4902-46a6-b1ff-fa69263f8302"
          },
          {
            "name": "LIMITE",
            "expression": "[TT NAO PAGO] - 10",
            "formatString": "0",
            "lineageTag": "d8c6e074-8915-4db6-8af7-f7dba0130b9f"
          },
          {
            "name": "INTERMEDIARIO",
            "expression": "[TT NAO PAGO] - 30",
            "formatString": "0",
            "lineageTag": "f57adabe-156a-4bab-990c-64de63082dc1"
          },
          {
            "name": "TT MATRI LIMITE",
            "expression": "[TT NAO PAGO] - 5",
            "formatString": "0",
            "lineageTag": "edb288d8-6f11-458c-93e4-0b40c7490275"
          },
          {
            "name": "TT NAO PAGO",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(COUNTA(f_BASE[Mensalidade])",
              "            ,FILTER(dim_situacao,dim_situacao[Situação] = \"Não Pago\"))",
              "",
              ""
            ],
            "lineageTag": "358b07c7-8a65-423c-ab66-dc657c669043"
          },
          {
            "name": "ticket medio",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "AVERAGE(f_BASE[Mensalidade])",
              "              "
            ],
            "lineageTag": "35e87e74-a07e-49cf-ab3c-8d5945296bae"
          }
        ],
        "partitions": [
          {
            "name": "MEDIDAS FINANCEIRA",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}